### ISSUE TITLE
Consider adding a LICENSE

### ISSUE THREAD

**Issue by motiejus** [ajbouh/bazel-zig-cc#1]
First of all, like discussed privately, this is a useful starting point for a Bazel zig toolchain. Thank you for it.

Consider adding a LICENSE to help future contributors understand what they are basing their work upon.

**Comment by ajbouh** [comment]
Thanks for the ping! I intend to add an open source license to this project (probably MIT)

**Comment by sskras** [comment]
@ajbouh, in case your decision is still in progress _and_ you would like it to be short, clear for _both_ law and software folks, I suggest you to consider the Blue Oak model license:
https://blueoakcouncil.org/2019/03/06/model.html

I think it does the best we can get (in the world of F/LOSS) to maximize the degree of legal completeness of the permissive license. That is, both in the I.P. law (copyright, patents) and in the Contract law (warranties, liabilities, formations):
https://blueoakcouncil.org/primer

One of its' creators, Kyle E. Mitchell did even a provocative take on the related old-school / earlier licenses:
https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html

Sure, there were some legal concerns risen (mostly by non-lawyers) in the past about potential legal issues, such as ...

* potential of assigning the cost of patent infringement done by one contributor to all contributors that also hold patents albeit unrelated:
https://opensource.stackexchange.com/questions/13890/blue-oak-model-license-vs-bsd-2-clause-plus-patent-license

* being untested in law departments and courts (which is natural given its' young age):
https://news.ycombinator.com/item?id=19347797

* being too focused into US jurisdiction (or so, sorry for my weak English):
https://news.ycombinator.com/item?id=19347898

* some other one details of which I already forgot:
http://hackerpublicradio.org/eps.php?id=2809

I still think the license is very much worth a try.
